
- name: pull code
  git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_dir }}"
    update: yes
    version: "{{ branch }}"
  
- name: docker-compose down
  command: docker-compose down
  args:
    chdir: "{{ repo_dir }}"
  ignore_errors: yes

- name: docker-compose up
  command: docker-compose -f docker-compose.production.yaml up -d
  args:
    chdir: "{{ repo_dir }}"
  environment:
    docker_image_tag: "{{ docker_image_tag }}"