name: ci

on:
  push:
    branches: [main]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v3

      - name: declare variables
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha::$(git rev-parse HEAD)"
        
      - name: login docker
        uses: docker/login-action@v1.14.0
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_PAT }}
        
      - name: build and push
        uses: docker/build-push-action@v2.9.0
        with:
          push: true
          tags: ${{ secrets.DOCKER_USER_NAME}}/readaily:${{ steps.vars.outputs.sha }}
      
      - name: run ansible deploy
        uses: dawidd6/action-ansible-playbook@v2.5.0
        with:
          playbook: provision/playbook.yaml
          key: ${{ secrets.ssh_key }}
          options: |
            --inventory provision/hosts.ini
            --extra-vars docker_image_tag=${{ steps.vars.outputs.sha }}
